# Generated by Django 5.2.7 on 2025-10-13 18:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название груза', max_length=255)),
                ('cargo_type', models.CharField(choices=[('general', 'Генеральный груз'), ('bulk', 'Насыпной груз'), ('liquid', 'Жидкий груз'), ('container', 'Контейнер'), ('refrigerated', 'Рефрижераторный'), ('dangerous', 'Опасный груз'), ('oversized', 'Крупногабаритный'), ('animals', 'Животные'), ('perishable', 'Скоропортящийся'), ('other', 'Другой')], max_length=40)),
                ('cargo_weight', models.FloatField(help_text='Вес груза в килограммах', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('cargo_volume', models.FloatField(help_text='Объем груза в метрах кубических', validators=[django.core.validators.MinValueValidator(0.001)])),
                ('description', models.CharField(blank=True, help_text='Описание груза', max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_address', models.CharField(help_text='Адрес начала маршрута', max_length=255)),
                ('end_address', models.CharField(help_text='Адрес конца маршрута', max_length=255)),
                ('distance', models.FloatField(help_text='Расстояние между адресами в километрах')),
                ('duration', models.FloatField(help_text='Время в пути в минутах')),
                ('loading_date', models.DateTimeField(blank=True, help_text='Дата погрузки', null=True)),
                ('price', models.FloatField(blank=True, help_text='Цена за заказ в рублях', null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.cargo')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['producer', 'created_at'], name='orders_orde_produce_d3dea2_idx'), models.Index(fields=['loading_date'], name='orders_orde_loading_4a48c9_idx')],
            },
        ),
    ]
