# Generated by Django 5.2.7 on 2025-10-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='duration',
            field=models.FloatField(blank=True, help_text='Время в пути в минутах', null=True),
        ),
    ]
