# Generated by Django 5.2.7 on 2025-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='ati_id',
            field=models.BigIntegerField(blank=True, help_text='ID груза на ATI.SU', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ati_id',
            field=models.BigIntegerField(blank=True, help_text='ID заказа (deal) на ATI.SU', null=True),
        ),
    ]
