# Generated by Django 5.2.7 on 2025-10-27 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cargo_ati_id_order_ati_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo_type_rools',
            field=models.CharField(blank=True, choices=[('liquid_bulk', 'Наливной'), ('break_bulk', 'Навалочный'), ('dry_bulk', 'Насыпной'), ('groupage', 'Сборный и разный груз'), ('oversized', 'Негабаритный'), ('container', 'Контейнер'), ('eur_pallet', 'EUR-паллеты'), ('fin_pallet', 'FIN-паллеты'), ('oth_pallet', 'Особые паллеты'), ('bag', 'Мешки'), ('big_bag', 'Биг-бэги'), ('icb', 'Еврокубы'), ('carton', 'Коробки'), ('barrel', 'Бочки'), ('roll', 'Рулоны'), ('reel', 'Барабаны'), ('coil', 'Бухта / Бунт'), ('crate', 'Ящики')], default='oversized', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Количество груза', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='order',
            name='rools_id',
            field=models.BigIntegerField(blank=True, help_text='ID заказа на ROOLS', null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_type',
            field=models.CharField(choices=[('general', 'Генеральный груз'), ('bulk', 'Насыпной груз'), ('liquid', 'Жидкий груз'), ('container', 'Контейнер'), ('refrigerated', 'Рефрижераторный'), ('dangerous', 'Опасный груз'), ('oversized', 'Крупногабаритный'), ('animals', 'Животные'), ('perishable', 'Скоропортящийся'), ('other', 'Другой')], default='general', max_length=40),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_volume',
            field=models.FloatField(blank=True, help_text='Объем груза в метрах кубических', null=True, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_weight',
            field=models.FloatField(blank=True, help_text='Вес груза в килограммах', null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
