# Generated by Django 5.2.7 on 2025-10-27 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cargo_cargo_type_rools_cargo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('POSTED', 'Опубликован'), ('COMPLETED', 'Выполнен'), ('CLOSED', 'Закрыт')], default='DRAFT', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='unloading_date',
            field=models.DateTimeField(blank=True, help_text='Дата разгрузки', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.FloatField(blank=True, help_text='Расстояние между адресами в километрах', null=True),
        ),
        migrations.CreateModel(
            name='CargoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cargo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
