# Generated by Django 5.2.7 on 2025-10-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_status_order_unloading_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rools_id',
            field=models.CharField(blank=True, help_text='ID заказа на ROOLS', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cargoorder',
            unique_together={('cargo', 'order')},
        ),
    ]
