# Generated by Django 5.2.7 on 2025-11-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_rools_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('POSTED', 'Опубликован'), ('CONFIRMATION', 'Утверждение'), ('COMPLETED', 'Выполнен'), ('CLOSED', 'Закрыт')], default='DRAFT', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
