# Generated by Django 5.2.7 on 2025-10-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatfile',
            name='file_type',
            field=models.CharField(help_text='Тип файла', max_length=255),
        ),
    ]
