# Generated by Django 5.2.7 on 2025-10-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_cargo_ati_id_order_ati_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(help_text='Название перевозчика', max_length=255)),
                ('carrier_inn', models.CharField(help_text='ИНН перевозчика', max_length=12)),
                ('carrier_rating', models.FloatField(help_text='Рейтинг перевозчика (0-5)')),
                ('price', models.FloatField(help_text='Цена предложения')),
                ('delivery_time', models.IntegerField(help_text='Время доставки в часах')),
                ('reliability_score', models.FloatField(help_text='Коэффициент надежности (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_offers', to='orders.order')),
            ],
            options={
                'ordering': ['-reliability_score', 'price'],
            },
        ),
        migrations.CreateModel(
            name='TransportResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_id', models.IntegerField(help_text='ID перевозчика')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('completed', 'Завершено')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Комментарий перевозчика', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='integrations.transportoffer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
