# Generated by Django 5.2.7 on 2025-10-21 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('orders', '0003_cargo_ati_id_order_ati_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportoffer',
            name='cargo_type',
            field=models.CharField(blank=True, help_text='Тип груза', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='cargo_volume',
            field=models.FloatField(blank=True, help_text='Объем груза в м³', null=True),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='cargo_weight',
            field=models.FloatField(blank=True, help_text='Вес груза в кг', null=True),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='distance',
            field=models.IntegerField(blank=True, help_text='Расстояние в км', null=True),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='from_city',
            field=models.CharField(blank=True, help_text='Город отправления', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='to_city',
            field=models.CharField(blank=True, help_text='Город назначения', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transportoffer',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Заказ (если привязан)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_offers', to='orders.order'),
        ),
    ]
