# Generated by Django 5.2.7 on 2025-10-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_transportoffer_cargo_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportoffer',
            name='distance',
        ),
    ]
