# Generated by Django 5.2.7 on 2025-10-21 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_remove_transportoffer_distance'),
        ('orders', '0003_cargo_ati_id_order_ati_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportresponse',
            name='carrier_id',
        ),
        migrations.AddField(
            model_name='transportresponse',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transport_responses', to='orders.order'),
            preserve_default=False,
        ),
    ]
