# Generated by Django 5.2.7 on 2025-10-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_remove_transportresponse_carrier_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportoffer',
            name='price',
            field=models.FloatField(blank=True, help_text='Цена предложения', null=True),
        ),
    ]
