# Generated by Django 5.2.7 on 2025-10-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_transportoffer_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportoffer',
            options={'ordering': ['-reliability_score']},
        ),
        migrations.RemoveField(
            model_name='transportoffer',
            name='price',
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='price_per_km',
            field=models.FloatField(default=10, help_text='Цена за 1 км пути в рублях'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportresponse',
            name='price',
            field=models.FloatField(blank=True, help_text='Итоговая цена предложения', null=True),
        ),
    ]
